# Task sequence definitions for continual learning experiments
#
# All 24 permutations of 4 tasks

sequences:
  sequence1: [LiftCube, OpenDoor, OpenDrawer, PushButton]
  sequence2: [LiftCube, OpenDoor, PushButton, OpenDrawer]
  sequence3: [LiftCube, OpenDrawer, OpenDoor, PushButton]
  sequence4: [LiftCube, OpenDrawer, PushButton, OpenDoor]
  sequence5: [LiftCube, PushButton, OpenDoor, OpenDrawer]
  sequence6: [LiftCube, PushButton, OpenDrawer, OpenDoor]
  sequence7: [OpenDoor, LiftCube, OpenDrawer, PushButton]
  sequence8: [OpenDoor, LiftCube, PushButton, OpenDrawer]
  sequence9: [OpenDoor, OpenDrawer, LiftCube, PushButton]
  sequence10: [OpenDoor, OpenDrawer, PushButton, LiftCube]
  sequence11: [OpenDoor, PushButton, LiftCube, OpenDrawer]
  sequence12: [OpenDoor, PushButton, OpenDrawer, LiftCube]
  sequence13: [OpenDrawer, LiftCube, OpenDoor, PushButton]
  sequence14: [OpenDrawer, LiftCube, PushButton, OpenDoor]
  sequence15: [OpenDrawer, OpenDoor, LiftCube, PushButton]
  sequence16: [OpenDrawer, OpenDoor, PushButton, LiftCube]
  sequence17: [OpenDrawer, PushButton, LiftCube, OpenDoor]
  sequence18: [OpenDrawer, PushButton, OpenDoor, LiftCube]
  sequence19: [PushButton, LiftCube, OpenDoor, OpenDrawer]
  sequence20: [PushButton, LiftCube, OpenDrawer, OpenDoor]
  sequence21: [PushButton, OpenDoor, LiftCube, OpenDrawer]
  sequence22: [PushButton, OpenDoor, OpenDrawer, LiftCube]
  sequence23: [PushButton, OpenDrawer, LiftCube, OpenDoor]
  sequence24: [PushButton, OpenDrawer, OpenDoor, LiftCube]
