# Task sequence definitions for continual learning experiments
#
# All 24 permutations of 4 tasks

sequences:
  sequence7: [OpenDoor, LiftCube, OpenDrawer, PushButton]
  sequence9: [OpenDoor, OpenDrawer, LiftCube, PushButton]
  sequence24: [PushButton, OpenDrawer, OpenDoor, LiftCube]
