# Task sequence definitions for continual learning experiments
#
# All 24 permutations of 4 tasks

sequences:
  sequence7: [OpenDoor, PushCuboid, OpenDrawer, PushButton]
  sequence8: [OpenDoor, PushCuboid, PushButton, OpenDrawer]
  sequence9: [OpenDoor, OpenDrawer, PushCuboid, PushButton]
  sequence10: [OpenDoor, OpenDrawer, PushButton, PushCuboid]
  sequence11: [OpenDoor, PushButton, PushCuboid, OpenDrawer]
  sequence12: [OpenDoor, PushButton, OpenDrawer, PushCuboid]
  sequence13: [OpenDrawer, PushCuboid, OpenDoor, PushButton]
  sequence14: [OpenDrawer, PushCuboid, PushButton, OpenDoor]
  sequence15: [OpenDrawer, OpenDoor, PushCuboid, PushButton]
  sequence16: [OpenDrawer, OpenDoor, PushButton, PushCuboid]
  sequence17: [OpenDrawer, PushButton, PushCuboid, OpenDoor]
  sequence18: [OpenDrawer, PushButton, OpenDoor, PushCuboid]
  sequence19: [PushButton, PushCuboid, OpenDoor, OpenDrawer]
  sequence20: [PushButton, PushCuboid, OpenDrawer, OpenDoor]
  sequence21: [PushButton, OpenDoor, PushCuboid, OpenDrawer]
  sequence22: [PushButton, OpenDoor, OpenDrawer, PushCuboid]
  sequence23: [PushButton, OpenDrawer, PushCuboid, OpenDoor]
  sequence24: [PushButton, OpenDrawer, OpenDoor, PushCuboid]
  sequence1: [PushCuboid, OpenDoor, OpenDrawer, PushButton]
  sequence2: [PushCuboid, OpenDoor, PushButton, OpenDrawer]
  sequence3: [PushCuboid, OpenDrawer, OpenDoor, PushButton]
  sequence4: [PushCuboid, OpenDrawer, PushButton, OpenDoor]
  sequence5: [PushCuboid, PushButton, OpenDoor, OpenDrawer]
  sequence6: [PushCuboid, PushButton, OpenDrawer, OpenDoor]
